blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/rhwendt/enphase-exporter/discussions
    about: Ask questions or start a discussion about the exporter
  - name: Enphase API Documentation
    url: https://github.com/Matthew1471/Enphase-API
    about: Community documentation of the Enphase local API
