# Prometheus config for local testing with docker-compose
global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'enphase-exporter'
    static_configs:
      - targets: ['enphase-exporter:9090']
    metrics_path: /metrics
