apiVersion: v1
kind: Service
metadata:
  name: enphase-exporter
  labels:
    app.kubernetes.io/name: enphase-exporter
    app.kubernetes.io/component: exporter
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 9090
      targetPort: http-metrics
      protocol: TCP
  selector:
    app.kubernetes.io/name: enphase-exporter
